from __future__ import annotations

from typing import Any

from config import TARGET_CITIES

OFFICIAL_SEED_URLS = [
    {
        "url": "https://www.hud.gov/states/florida",
        "title": "HUD Florida housing resources",
        "source_quality": "HUD/USDA/FHFC",
        "source_category": "hud",
        "city": "Unknown",
        "county": "Unknown",
    },
    {
        "url": "https://rdmfhrentals.sc.egov.usda.gov/",
        "title": "USDA Rural Development MFH Rentals",
        "source_quality": "HUD/USDA/FHFC",
        "source_category": "usda",
        "city": "Unknown",
        "county": "Unknown",
    },
    {
        "url": "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=069&st=12",
        "title": "USDA Lake County multifamily rentals",
        "source_quality": "HUD/USDA/FHFC",
        "source_category": "usda",
        "city": "Leesburg",
        "county": "Lake County",
    },
    {
        "url": "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=119&st=12",
        "title": "USDA Sumter County multifamily rentals",
        "source_quality": "HUD/USDA/FHFC",
        "source_category": "usda",
        "city": "Wildwood",
        "county": "Sumter County",
    },
    {
        "url": "https://floridahousingsearch.org/",
        "title": "Florida Housing Search",
        "source_quality": "HUD/USDA/FHFC",
        "source_category": "state_listing",
        "city": "Unknown",
        "county": "Unknown",
    },
    {
        "url": "https://sumtercountyfl.gov/87/Housing",
        "title": "Sumter County Housing division",
        "source_quality": "government",
        "source_category": "county_housing",
        "city": "Wildwood",
        "county": "Sumter County",
    },
    {
        "url": "https://sumtercountyfl.gov/243/Rental-Assistance",
        "title": "Sumter County rental assistance",
        "source_quality": "government",
        "source_category": "county_housing",
        "city": "Wildwood",
        "county": "Sumter County",
    },
    {
        "url": "https://www.sumtercountyfl.gov/246/Rental-Assistance-Resources",
        "title": "Sumter County rental assistance resources",
        "source_quality": "government",
        "source_category": "county_housing",
        "city": "Wildwood",
        "county": "Sumter County",
    },
    {
        "url": "https://lakecountyfl.gov/housing",
        "title": "Lake County housing and community services",
        "source_quality": "government",
        "source_category": "county_housing",
        "city": "Leesburg",
        "county": "Lake County",
    },
    {
        "url": "https://www.citruscounty.gov/departments/community_services/housing_services/housing_choice_voucher_program/index.php",
        "title": "Citrus County Housing Choice Voucher Program",
        "source_quality": "housing_authority",
        "source_category": "housing_authority",
        "city": "Wildwood",
        "county": "Sumter County",
    },
]


KNOWN_PROPERTY_LEADS: list[dict[str, Any]] = [
    {
        "property_name": "Wildwood Commons",
        "property_type": "Unknown",
        "address": "1000 Lee St",
        "city": "Wildwood",
        "county": "Sumter County",
        "state": "FL",
        "zip": "34785",
        "phone": "(352) 748-0047",
        "source_urls": [
            "https://www.sumtercountyfl.gov/246/Rental-Assistance-Resources",
            "https://www.sumtercountyfl.gov/DocumentCenter/View/29964/Sumter-County-Multifamily-Analysis-Final-Version-06202018",
        ],
        "source_quality": "government",
        "housing_authority_or_agency": "Sumter County Housing",
        "program_type": "Unknown affordable rental",
        "notes": "Listed by Sumter County as rental assistance provider and in county multifamily inventory.",
    },
    {
        "property_name": "Wildwood Terrace",
        "property_type": "Unknown",
        "address": "500 Gilliam St",
        "city": "Wildwood",
        "county": "Sumter County",
        "state": "FL",
        "zip": "34785",
        "phone": "(352) 748-0013",
        "source_urls": [
            "https://www.sumtercountyfl.gov/246/Rental-Assistance-Resources",
            "https://www.sumtercountyfl.gov/DocumentCenter/View/29964/Sumter-County-Multifamily-Analysis-Final-Version-06202018",
        ],
        "source_quality": "government",
        "housing_authority_or_agency": "Sumter County Housing",
        "program_type": "Unknown affordable rental",
        "notes": "Listed by Sumter County as rental assistance provider and in county multifamily inventory.",
    },
    {
        "property_name": "Wildwood Townhomes",
        "property_type": "Unknown",
        "address": "301 E Gulf Atlantic Hwy",
        "city": "Wildwood",
        "county": "Sumter County",
        "state": "FL",
        "zip": "34785",
        "phone": "(352) 748-5677",
        "source_urls": [
            "https://www.sumtercountyfl.gov/246/Rental-Assistance-Resources",
            "https://www.sumtercountyfl.gov/DocumentCenter/View/29964/Sumter-County-Multifamily-Analysis-Final-Version-06202018",
        ],
        "source_quality": "government",
        "housing_authority_or_agency": "Sumter County Housing",
        "program_type": "Unknown affordable rental",
        "notes": "Listed by Sumter County as rental assistance provider and in county multifamily inventory.",
    },
    {
        "property_name": "Bushnell Garden Apartments",
        "property_type": "Unknown",
        "address": "200 Jumper St S",
        "city": "Bushnell",
        "county": "Sumter County",
        "state": "FL",
        "zip": "33513",
        "phone": "(352) 793-4838",
        "source_urls": [
            "https://www.sumtercountyfl.gov/246/Rental-Assistance-Resources",
            "https://www.sumtercountyfl.gov/DocumentCenter/View/29964/Sumter-County-Multifamily-Analysis-Final-Version-06202018",
        ],
        "source_quality": "government",
        "housing_authority_or_agency": "Sumter County Housing",
        "program_type": "Unknown affordable rental",
        "notes": "Outside primary city list but near the target areas and listed by Sumter County as rental assistance provider.",
    },
    {
        "property_name": "Bushnell Gardens II",
        "property_type": "Unknown",
        "address": "1000 Meadows Cir",
        "city": "Bushnell",
        "county": "Sumter County",
        "state": "FL",
        "zip": "33513",
        "phone": "(352) 793-4838",
        "source_urls": [
            "https://www.sumtercountyfl.gov/DocumentCenter/View/29964/Sumter-County-Multifamily-Analysis-Final-Version-06202018",
        ],
        "source_quality": "government",
        "housing_authority_or_agency": "Sumter County Housing",
        "program_type": "Unknown affordable rental",
        "notes": "County multifamily inventory lead; verify with property directly.",
    },
    {
        "property_name": "Panasoffkee Family Apartments",
        "property_type": "Family",
        "address": "910 CR 482N",
        "city": "Lake Panasoffkee",
        "county": "Sumter County",
        "state": "FL",
        "zip": "33538",
        "phone": "(352) 793-2288",
        "source_urls": [
            "https://www.sumtercountyfl.gov/246/Rental-Assistance-Resources",
            "https://www.sumtercountyfl.gov/DocumentCenter/View/29964/Sumter-County-Multifamily-Analysis-Final-Version-06202018",
        ],
        "source_quality": "government",
        "housing_authority_or_agency": "Sumter County Housing",
        "program_type": "Unknown affordable rental",
        "notes": "County multifamily inventory indicates family-focused property at same site as senior apartments.",
    },
    {
        "property_name": "Panasoffkee Senior Apartments",
        "property_type": "Senior 62+",
        "address": "910 CR 482N",
        "city": "Lake Panasoffkee",
        "county": "Sumter County",
        "state": "FL",
        "zip": "33538",
        "phone": "(352) 793-2288",
        "source_urls": [
            "https://www.sumtercountyfl.gov/246/Rental-Assistance-Resources",
            "https://www.sumtercountyfl.gov/DocumentCenter/View/29964/Sumter-County-Multifamily-Analysis-Final-Version-06202018",
        ],
        "source_quality": "government",
        "housing_authority_or_agency": "Sumter County Housing",
        "program_type": "Unknown affordable rental",
        "notes": "County multifamily inventory indicates senior-focused property at same site as family apartments.",
    },
    {
        "property_name": "Misty Wood Apartments",
        "property_type": "Unknown",
        "address": "205 Jumper Dr N",
        "city": "Bushnell",
        "county": "Sumter County",
        "state": "FL",
        "zip": "33513",
        "phone": "(352) 793-8211",
        "source_urls": [
            "https://www.sumtercountyfl.gov/246/Rental-Assistance-Resources",
            "https://www.sumtercountyfl.gov/DocumentCenter/View/29964/Sumter-County-Multifamily-Analysis-Final-Version-06202018",
        ],
        "source_quality": "government",
        "housing_authority_or_agency": "Sumter County Housing",
        "program_type": "Unknown affordable rental",
        "notes": "Sumter County rental assistance provider lead.",
    },
    {
        "property_name": "Lake Sumter Reserve Apartment Homes",
        "property_type": "Mixed Affordable",
        "address": "10840 NE 89th Drive",
        "city": "Lady Lake",
        "county": "Sumter County",
        "state": "FL",
        "zip": "32162",
        "phone": "",
        "source_urls": [
            "https://www.sumtercountyfl.gov/AgendaCenter/ViewFile/Item/23512?fileID=57591",
        ],
        "source_quality": "government",
        "housing_authority_or_agency": "Sumter County Housing",
        "program_type": "SHIP / FHFC funded affordable rental",
        "notes": "County SHIP agenda references FHFC and SHIP funding for this apartment community.",
    },
    {
        "property_name": "Fruitland Acres LTD",
        "property_type": "USDA RD",
        "address": "NOT FOUND / NEEDS CALL",
        "city": "Fruitland Park",
        "county": "Lake County",
        "state": "FL",
        "zip": "",
        "phone": "",
        "source_urls": [
            "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=069&st=12",
        ],
        "source_quality": "HUD/USDA/FHFC",
        "program_type": "USDA RD 515",
        "notes": "Listed on USDA Rural Development Lake County property list.",
    },
    {
        "property_name": "Mirror Lake Manor",
        "property_type": "USDA RD",
        "address": "NOT FOUND / NEEDS CALL",
        "city": "Fruitland Park",
        "county": "Lake County",
        "state": "FL",
        "zip": "",
        "phone": "",
        "source_urls": [
            "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=069&st=12",
        ],
        "source_quality": "HUD/USDA/FHFC",
        "program_type": "USDA RD 515",
        "notes": "Listed on USDA Rural Development Lake County property list.",
    },
    {
        "property_name": "Lake North Apts II",
        "property_type": "USDA RD",
        "address": "NOT FOUND / NEEDS CALL",
        "city": "Lady Lake",
        "county": "Lake County",
        "state": "FL",
        "zip": "",
        "phone": "",
        "source_urls": [
            "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=069&st=12",
        ],
        "source_quality": "HUD/USDA/FHFC",
        "program_type": "USDA RD 515",
        "notes": "Listed on USDA Rural Development Lake County property list.",
    },
    {
        "property_name": "Lake North Apts LTD",
        "property_type": "USDA RD",
        "address": "NOT FOUND / NEEDS CALL",
        "city": "Lady Lake",
        "county": "Lake County",
        "state": "FL",
        "zip": "",
        "phone": "",
        "source_urls": [
            "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=069&st=12",
        ],
        "source_quality": "HUD/USDA/FHFC",
        "program_type": "USDA RD 515",
        "notes": "Listed on USDA Rural Development Lake County property list.",
    },
    {
        "property_name": "Lakewood Villas",
        "property_type": "USDA RD",
        "address": "NOT FOUND / NEEDS CALL",
        "city": "Lady Lake",
        "county": "Lake County",
        "state": "FL",
        "zip": "",
        "phone": "",
        "source_urls": [
            "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=069&st=12",
        ],
        "source_quality": "HUD/USDA/FHFC",
        "program_type": "USDA RD 515",
        "notes": "Listed on USDA Rural Development Lake County property list.",
    },
    {
        "property_name": "Montclair Village",
        "property_type": "USDA RD",
        "address": "NOT FOUND / NEEDS CALL",
        "city": "Leesburg",
        "county": "Lake County",
        "state": "FL",
        "zip": "",
        "phone": "",
        "source_urls": [
            "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=069&st=12",
        ],
        "source_quality": "HUD/USDA/FHFC",
        "program_type": "USDA RD 515",
        "notes": "Listed on USDA Rural Development Lake County property list.",
    },
    {
        "property_name": "Palm Brook Apts LTD",
        "property_type": "USDA RD",
        "address": "NOT FOUND / NEEDS CALL",
        "city": "Leesburg",
        "county": "Lake County",
        "state": "FL",
        "zip": "",
        "phone": "",
        "source_urls": [
            "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=069&st=12",
        ],
        "source_quality": "HUD/USDA/FHFC",
        "program_type": "USDA RD 515",
        "notes": "Listed on USDA Rural Development Lake County property list.",
    },
    {
        "property_name": "Pepper Tree Apts",
        "property_type": "USDA RD",
        "address": "NOT FOUND / NEEDS CALL",
        "city": "Leesburg",
        "county": "Lake County",
        "state": "FL",
        "zip": "",
        "phone": "",
        "source_urls": [
            "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=069&st=12",
        ],
        "source_quality": "HUD/USDA/FHFC",
        "program_type": "USDA RD 515",
        "notes": "Listed on USDA Rural Development Lake County property list.",
    },
    {
        "property_name": "Pepper Tree Apts II",
        "property_type": "USDA RD",
        "address": "NOT FOUND / NEEDS CALL",
        "city": "Leesburg",
        "county": "Lake County",
        "state": "FL",
        "zip": "",
        "phone": "",
        "source_urls": [
            "https://rdmfhrentals.sc.egov.usda.gov/RDMFHRentals/projectservlet?cnty=069&st=12",
        ],
        "source_quality": "HUD/USDA/FHFC",
        "program_type": "USDA RD 515",
        "notes": "Listed on USDA Rural Development Lake County property list.",
    },
]


def get_official_seed_urls() -> list[dict[str, Any]]:
    return [dict(item) for item in OFFICIAL_SEED_URLS]


def get_known_property_leads() -> list[dict[str, Any]]:
    return [dict(item) for item in KNOWN_PROPERTY_LEADS]


def curated_seed_urls_text() -> str:
    lines = [
        "# Add one URL per line. Blank lines and comments are ignored.",
        "# Official sources are already built in; this file is for manual additions.",
    ]
    lines.extend(item["url"] for item in OFFICIAL_SEED_URLS)
    return "\n".join(lines) + "\n"


def city_is_target(city: str) -> bool:
    return city in TARGET_CITIES
